[project]
name = "poepalettedata"
version = "0.0.1"
requires-python = "==3.14.*"
dependencies = [
    "boto3",
    "sentry-sdk",
    "humanize",
    "requests",
    "emoji",
]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "boto3-stubs",
    "types-requests",
]

[tool.uv]
package = false
